import BootstrapClient from '@/components/BootstrapClient.js'
import 'bootstrap/dist/css/bootstrap.css'
import './styles/globals.scss'
import { UserProvider } from '@auth0/nextjs-auth0/client'

export const metadata = {
  title: "Mtuan's Portfolio",
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <UserProvider>
          {children}
          <BootstrapClient />
        </UserProvider>
      </body>
    </html>
  )
}
